{
  "app_entry": {},
  "conda_platforms": [
    "noarch"
  ],
  "full_name": "conda-forge/napari-error-reporter",
  "owner": {
    "description": "A community-led collection of recipes, build infrastructure, and distributions for the conda package manager.",
    "url": "",
    "company": "",
    "user_type": "org",
    "location": "",
    "login": "conda-forge",
    "created_at": "2015-04-11 10:15:08.727000+00:00",
    "name": "conda-forge"
  },
  "home": "https://github.com/tlambert03/napari-error-reporter",
  "source_git_url": null,
  "source_git_tag": null,
  "app_type": {},
  "upvoted": 0,
  "id": "62a723cbaae6eba13a8cee31",
  "app_summary": {},
  "public": true,
  "revision": 4,
  "files": [
    {
      "size": 16769,
      "upload_time": "2022-06-13 11:47:21.139000+00:00",
      "description": null,
      "basename": "noarch/napari-error-reporter-0.3.0-pyhd8ed1ab_0.tar.bz2",
      "version": "0.3.0",
      "download_url": "//api.anaconda.org/download/conda-forge/napari-error-reporter/0.3.0/noarch/napari-error-reporter-0.3.0-pyhd8ed1ab_0.tar.bz2",
      "labels": [
        "main"
      ],
      "distribution_type": "conda",
      "attrs": {
        "build_number": 0,
        "license": "BSD-3-Clause",
        "has_prefix": false,
        "noarch": "python",
        "machine": null,
        "platform": null,
        "depends": [
          "appdirs",
          "python >=3.8",
          "qtpy",
          "sentry-sdk"
        ],
        "build": "pyhd8ed1ab_0",
        "timestamp": 1655120807708,
        "arch": null,
        "operatingsystem": null,
        "target-triplet": "None-any-None",
        "subdir": "noarch",
        "constrains": []
      },
      "full_name": "conda-forge/napari-error-reporter/0.3.0/noarch/napari-error-reporter-0.3.0-pyhd8ed1ab_0.tar.bz2",
      "owner": "conda-forge",
      "sha256": "None",
      "type": "conda",
      "md5": "0d18c2b377c9b11cb765d6d77945485d"
    },
    {
      "size": 17641,
      "upload_time": "2022-06-22 09:39:39.050000+00:00",
      "description": null,
      "basename": "noarch/napari-error-reporter-0.3.1-pyhd8ed1ab_0.tar.bz2",
      "version": "0.3.1",
      "download_url": "//api.anaconda.org/download/conda-forge/napari-error-reporter/0.3.1/noarch/napari-error-reporter-0.3.1-pyhd8ed1ab_0.tar.bz2",
      "labels": [
        "main"
      ],
      "distribution_type": "conda",
      "attrs": {
        "build_number": 0,
        "license": "BSD-3-Clause",
        "has_prefix": false,
        "noarch": "python",
        "machine": null,
        "platform": null,
        "depends": [
          "appdirs",
          "python >=3.8",
          "qtpy",
          "sentry-sdk"
        ],
        "build": "pyhd8ed1ab_0",
        "timestamp": 1655890753335,
        "arch": null,
        "operatingsystem": null,
        "target-triplet": "None-any-None",
        "subdir": "noarch",
        "constrains": []
      },
      "full_name": "conda-forge/napari-error-reporter/0.3.1/noarch/napari-error-reporter-0.3.1-pyhd8ed1ab_0.tar.bz2",
      "owner": "conda-forge",
      "sha256": "None",
      "type": "conda",
      "md5": "73ad0a0149401b4cb13bff1c734a87c0"
    }
  ],
  "package_types": [
    "conda"
  ],
  "description": "",
  "releases": [
    {
      "version": "0.3.0",
      "distributions": [],
      "full_name": "conda-forge/napari-error-reporter/0.3.0"
    },
    {
      "version": "0.3.1",
      "distributions": [],
      "full_name": "conda-forge/napari-error-reporter/0.3.1"
    }
  ],
  "html_url": "http://anaconda.org/conda-forge/napari-error-reporter",
  "builds": [
    "pyhd8ed1ab_0"
  ],
  "watchers": 1,
  "dev_url": null,
  "name": "napari-error-reporter",
  "license": "BSD-3-Clause",
  "versions": [
    "0.3.0",
    "0.3.1"
  ],
  "url": "http://api.anaconda.org/packages/conda-forge/napari-error-reporter",
  "created_at": "2022-06-13 11:47:20.647000+00:00",
  "modified_at": "2022-06-22 09:39:40.346000+00:00",
  "latest_version": "0.3.1",
  "summary": "Opt-in automated bug/error reporting for napari",
  "license_url": null,
  "doc_url": null
}